[2단계 자동차 미션] 코드 리뷰 부탁드립니다
SSAFY5thGwangJu4C/ssafy-java-racingcar pull request #12
Opened 2021-05-15 14:41 UTC by hyewon1012

생각했던것보다 시간이 오래걸렸습니다ㅠㅠ

1. 반복문을 사용한 로직에서 인덱스를 통해 접근했기때문에 stream 을 사용하지 않았는데 이 부분 피드백 부탁드릴께요ㅠㅠ
2. assertJ 의 예외처리를 구현할때 assertThatThrownBy(), assertThatExceptionOfType() 중에 어떤걸 사용하는게 더 보편적인가요? 저는 처음에 직접 클래스에서 throw new IllegalStateException("잘못된 사칙연산 기호가 포함되있습니다. ") 로 예외를 던진다음 assertThat(e.getMessage()).isEqualTo("잘못된 사칙연산 기호가 포함되있습니다."); 와 같이 처리해주었다가 힌트를 보고 다시바꿨습니다!

2021-05-15 15:36 UTC, kwj1270 requested changes
안녕하세요 혜원님!!
요구사항에 비해 생각보다 어려운 미션에 대해 빠르고 깔끔하게 코드를 구현해주셨군요 👍 
커밋 기록도 잘 남겨주셨고 이전에 비해 확실히 가독성이 많이 높아진 것이 느껴졌습니다. ☺️
(단, `fix` 는 버그 처리에만 사용하므로 수정시에는 `test`나 `feat` 으로 기록해주세요 😉)   
     
단, 몇 가지 생각해볼 점들이 있는 것 같아 피드백을 남겨볼게요.         
그리고 해당 부분에 대해서 앞으로 한 번 더 `request change`를 할 것 같은데   
빠르게 피드백 반영해주시고 다시 요청해주시면 좋을 것 같아요 :)  

열심히 달려주시는 모습이 너무 보기 좋고 점점 성장하시는 모습이 기대가 됩니다 :)   
앞으로도 화이팅합시다!!

2021-05-15 15:36 UTC, kwj1270 commented on src/main/java/step2/StringOperation.java
> +        if(input == null || input.equals("")) throw new IllegalArgumentException();
검증 기능을 추가해주셨군요 :) 💯 , 
이 부분에 대해서는 `public void validateEmpty()` 라는 메서드로 분리해보는 것은 어떨까요?  
그러면 `calculate()`라는 메서드 안에 `검증`이랑 `계산`이라는 2가지 기능이 분리 될 것이고   
위와 같이 빈 값이 입력되는 로직이 추가로 필요하다면 `validateEmpty()`를 호출하여 재사용할 수 있을 것 같네요!

2021-05-15 15:36 UTC, kwj1270 commented on src/main/java/step2/StringOperation.java
> +        int b = 0;
숫자 같은 경우는 언제든지 문제가 발생할 여지가 많아요 
예를 들면 `0` 앞에 `1`을 붙이면 `10`이 될 수 도 있고 `+-` 같은 기호를 잘못 붙이면 로직이 꼬일 수도 있죠   
이를 해결하기 위해 `상수`를 사용하는 방법은 어떨까요?   
그리고 [해당 사이트](https://zorba91.tistory.com/275)를 참고 해보시면 좋을 것 같아요 :)

2021-05-15 15:36 UTC, kwj1270 commented on src/main/java/step2/StringOperation.java
> +    }
각각의 메서드로 분리한 점 👍      
이 부분을 [전략 패턴](https://github.com/kwj1270/TIL_Seminar/blob/650c5eed892cf99e3ac4957d0bbfd3d29206f9d3/OCP%EC%99%80%20%EC%A0%84%EB%9E%B5%20%ED%8C%A8%ED%84%B4.md)을 사용해서 적용해보는 것은 어떨까요?   
[동영상](https://youtu.be/lJES5TQTTWE?t=232)    

```java
@FunctionalInterface
interface Operator {
    double apply(double x, double y);
}
```
```java
public class Addition implements Operator  {
    @Override
    double apply(double x, double y){ 
        return (x * y);
    }
}
```
```java
이외에 비슷한 클래스들...
```

2021-05-15 15:36 UTC, kwj1270 commented on src/test/java/step2/StringOperationTest.java
> +public class StringOperationTest {
테스트 코드는 정말 완벽하게 작성해주셨네요 💯 💯 💯 
주석, 각각의 연산자 테스트, 예외처리까지... 완벽한 테스트 클래스입니다 🥇

2021-05-15 15:36 UTC, kwj1270 commented on src/test/java/step2/StringOperationTest.java
> +    @NullAndEmptySource
처음 보는 레퍼런스네요!! 
저는 항상 null 값을 만들었는데 😂 
혜원님 덕분에 새로운 라이브러리 많이 배우네요 감사합니다 :)

2021-05-15 15:36 UTC, kwj1270 commented on src/main/java/step2/StringOperation.java
> +        }
switch/case 구문을 이용하셨군요!!
요구사항 명세서에는 기술되어 있지는 않지만  
`객체지향생활체조원칙`에서는 `switch/case`문을 금지하고 있어요 😢     
  
이 부분을 `if`구문만 사용하는 것으로 변경하면 어떨까요?

2021-05-15 15:45 UTC, kwj1270 commented on src/main/java/step2/StringOperation.java
> +        if(input == null || input.equals("")) throw new IllegalArgumentException();
```suggestion
        if(Objects.isNull(input) || String.isEmpty(input)) {
            throw new IllegalArgumentException();
        }
```
한 줄 코드라도 `{}`를 붙여주셔야 안정성이 높아지니 참고 부탁드리고요  
위와 같이 라이브러리를 이용하는 것도 좋을 것 같네요!!

2021-05-15 16:10 UTC, kwj1270 commented on src/main/java/step2/StringOperation.java
> +    }
더 좋게 구현하려면 `Math.계산 메서드`를 활용해도 될 것 같네요!

2021-05-16 04:51 UTC, hyewon1012 commented on src/main/java/step2/StringOperation.java
> +    }
오 그렇군요ㅠㅠ 우재님 저는 StringOperation 클래스를 final 로 선언했기때문에 인스턴스 메소드는 final 로 선언하지 않았습니다!! final class로 선언했기 때문에 메소드 오버라이딩이 아예 불가능하다고 생각했습니다!!

싱글톤 패턴에서는 이런 규약들이 존재하는건가요?! 많이 헷갈리네요 피드백 주시면 확실하게 정리하겠습니다..ㅎㅎ

2021-05-16 04:58 UTC, hyewon1012 commented on src/main/java/step2/StringOperation.java
> +    }
넵 저번에 알려주신건데..ㅠㅠ 수정하겠습니다!!

2021-05-16 05:16 UTC, hyewon1012 commented on src/main/java/step2/StringOperation.java
> +        int b = 0;
b는 변수 역할을 하기 때문에 초기화해준다는 의미로 사용했습니다!! for문을 돌면서 b에 값이 계속 바뀌어야 하기 때문에 이렇게 구현하였는데 이 코드에서 상수를 사용한다는건 어떤 의미인지 잘 모르겠습니다 ㅠㅡㅠ

2021-05-16 11:59 UTC, hyewon1012 commented on src/main/java/step2/StringOperation.java
> +        int b = 0;
매직넘버에 대해 처음으로 알게되었습니다!! 수정하겠습니다!! 감사합니다!!

2021-05-17 08:11 UTC, kwj1270 requested changes
조금씩 개선되가는 모습이 너무 보기 좋습니다.   
몇가지 피드백 남겨 놓을테니 지속적으로 확인하시면서 다시 구현해보시면 좋을 것 같아요 :)

2021-05-24 12:11 UTC, merged