[ssafy-java-racingcar] - step.2 문자열 계산기 코드리뷰 부탁드립니다.
SSAFY5thGwangJu4C/ssafy-java-racingcar pull request #13
Opened 2021-05-16 04:20 UTC by KimSeongKyu

안녕하세요 우재님. step.2 문자열 계산기 코드리뷰 부탁드립니다.

계산기는 계산기 역할만 해야 된다고 생각하여 계산 기능을 하는 StringCalculator 클래스와 
수식을 공백으로 분리하는 ExpressionTokenizer 클래스를 따로 두었습니다.

스트림을 사용하면서 기존의 for문에 비해 직관적인 코드가 되어 가독성이 훨씬 높아졌지만,
내부 반복이 아직은 어색하여 단순한 코드임에도 생각보다 작성하기가 어렵더군요. 아직 많이 부족함을 느낍니다 ㅎㅎ

그리고 계산을 하는 calculate의 로직을 스트림으로 처리할 수 있는지 궁금합니다.
처음에는 스트림으로 처리하려 했지만 배열 내에 연산자와 피연산자가 함께 있어 스트림으로 처리하지 못했습니다.
그래서 연산자 스트림과 피연산자 서로 다른 스트림으로 분리한 후 연산 로직을 처리해보려 했지만
내부 반복으로 인해 두 스트림을 이용해 하나의 연산을 하지 못했습니다.
이를 해결할 방법이 있다면 피드백 해주시면 감사하겠습니다 :)

2021-05-16 10:16 UTC, kwj1270 requested changes
안녕하세요 성규님 이번 미션도 아주 깔끔하게 코드를 작성해주셨군요 👍 👍 👍 
코드 한 줄 한 줄 세심히 작성하셨다는 느낌을 크게 받습니다.

우선 질문에 대한 답변을 드리자면 
`stream()`은 권장 사항이지 필수 사항은 아니에요.
설계에 따라서 `stream()`을 구현할 수 있는 방법은 있지만   
현재 단계에서는 적용하기 힘드므로 단순 for 구문으로도 작성해주셔도 괜찮을 것 같네요! 
그리고 for 같은 경우 인덱스를 명확히 표현하고자 할 때 사용하므로   
이번처럼 인덱스에 따라서 값을 가져오는 경우 for 가 더 적합할 수 있습니다 :)  

이외에 몇 가지 부분에서 고려해볼 점들에 대해서 피드백을 남겼어요
해당 부분에 대해서 고려해보시고 다시 PR 보내주세요!! 화이팅입니다. 💪

2021-05-16 10:16 UTC, kwj1270 commented on src/test/java/step1/StringUtilTest.java
> +        ;
```suggestion
        
```

2021-05-16 10:16 UTC, kwj1270 commented on src/test/java/step2/StringCalculatorTest.java
> +        });
주석을 위해 로직의 가독성을 떨어뜨릴 필요는 없을 것 같아요 :)
when and then 이런식으로 처리해줘도 됩니다 👍

2021-05-16 11:23 UTC, KimSeongKyu commented on src/main/java/step1/StringUtil.java
> +    private static final String COMMA = ",";
좋은 사이트 공유 감사합니다!😄
사이트를 참고해보니 ONE이라는 상수도 의미가 불분명한 것 같아 INDEX_AFTER_OPEN_BRACKET으로 수정해 보았습니다.
그리고 마찬가지로 substring 메소드의 파라미터 중 endIndex에 해당하는 부분도 식만 봤을때 의미가 명확하지 않아 메소드로 따로 분리하여 계산하는 식으로 리팩토링을 진행해봤습니다!

2021-05-16 12:08 UTC, kwj1270 commented on src/main/java/step2/ExpressionTokenizer.java
> +        }
@KimSeongKyu 
이 부분에 대해서 잘 못 언급했는데 `private`로 메서드를 만들어주면 좋을 것 같습니다 :)

2021-05-16 12:08 UTC, kwj1270 commented on src/main/java/step1/StringUtil.java
> +    private static final String COMMA = ",";
그 부분에 대해서는 따로 언급을 안 했는데 잘 파악해주셨네요! 💯

2021-05-16 16:28 UTC, KimSeongKyu commented
우재님 ; 하나까지 놓치지 않는 꼼꼼한 피드백 너무 감사합니다!!! 👍

피드백대로 매직 넘버를 없애기 위해 명확한 이름을 부여하려고 하다 보니 너무 당연하게 생각했던 내용들에 대해
왜? 라는 의문 부호가 붙기 시작하였고, 코드 한 줄 한 줄을 더욱 깊게 생각하고 작성하게 되었습니다.
그리고 전략 패턴이라는 새로운 개념을 적용하고 보니 코드가 이전보다 훨씬 분리되어 좋은 것 같습니다! :)

하지만 OperatorSelector를 구현하면서 마지막에는 null을 반환하게 되어 NPE를 방지하기 위해
Optional 클래스로 감싸 구현해 봤는데, 한 가지 딜레마에 빠지게 되었습니다.

처음에는 사칙 연산자를 선택할 때 
``` java
public final static Optional<Operator> selectOperator(final String operatorString) {
    if (operatorString.equals(ADD)) {
        return Optional.of(new AddOperator());
    }
    if (operatorString.equals(SUBTRACT)) {
        return Optional.of(new SubtractOperator());
    }
    if (operatorString.equals(MULTIPLY)) {
        return Optional.of(new MultiplyOperator());
    }
    if (operatorString.equals(DIVIDE)) {
        return Optional.of(new DivideOperator());
    }
    return null;
}
``` 
와 같이 주어진 사칙 연산자가 아닌 경우 null을 반환하고 연산자를 선택할 때
```java
private static Optional<Operator> operator;

public final static BigDecimal calculate(final String expression) {
        // ...
        operator =  Optional.ofNullable(OperatorSelector.selectOperator(operatorString))
                .orElseThrow(IllegalArgumentException::new);
    }
}
```
와 같이 사칙 연산자가 아니여서 null이 반환된 경우 IllegalArgument Exception을 발생시키려 했습니다.

하지만 이렇게 구현을 했을 경우 우재님이 피드백을 주신 것과 같이 calculate이라는 메소드가
예외 처리 기능까지 같이 담당하는 문제가 다시 발생하여 빈 Optional 객체를 반환하는 것으로 코드를 구현하였습니다.
Optional을 이용하여 null일 경우 예외를 발생 시키는 것은 좋은 개발 방식이라고 할 수 없는 걸까요?

2021-05-17 04:04 UTC, kwj1270 reviewed
이 부분에 대해서는 충분히 고민이 될 수 있는 내용인 것 같네요

정확히 말하자면 `null 인 경우라기 보다`는 `+`,`-`,`*`,`/` 을 `제외한 문구`가 입력 되었을 경우  
`Optional`의 `빈 값`을 반환하는 작업을 해주신걸로 보입니다.
그리고 `calculate()`에서는 빈 값인지 아닌지를 검증할 수 밖에 없어야겠죠   
  
사실 검증 로직을 분리하는 이유가 여럿 존재하는데   
맥락 뿐만 아니라 `프로덕션 코드`를 더럽힌다는 문제가 있기 때문입니다. 
```java
// 비즈니스로직에 검증로직이 들어가면서 코드를 더럽힌다.  
if(a == null) {
    throw new IllegalArgumentException();
}
```
하지만, `Optional` 같은 경우 예외처리까지 하나의 논리     
즉, 프로덕션 코드라고 인식을 하면서 사용하기에       
따로 메서드를 만들지 않고 기존 로직에 녹여내어 사용할 수 있는 것입니다.      
  
그렇기에 `Optional을 이용하여 null일 경우 예외를 발생 시키는 것은 좋은 개발 방식이라고 할 수 없는 걸까요?`
에 대한 답을 하자면 오히려 좋은 개발 방식이라고 말하고 싶네요 :)

2021-05-17 04:04 UTC, merged

2021-05-17 04:08 UTC, kwj1270 commented
@KimSeongKyu 
2단계 미션은 여기서 마치겠습니다 수고하셨어요 :)  
그럼에도 몇가지 생각해볼 점들에 대해서 코멘트 남겼으니 확인 부탁드리고
오늘 강의를 통해서 새롭게 얻은 이번 미션의 인사이트를 다음 PR때 반영해주면 좋을 것 같습니다.