[3단계 자동차 미션] 코드 리뷰 부탁드립니다
SSAFY5thGwangJu4C/ssafy-java-racingcar pull request #15
Opened 2021-05-24 12:09 UTC by hyewon1012

안녕하세요 우재님

2단계까지 진행하면서 배웠던 내용들을 최대한 적용시키려 시도해봤습니다!
(리팩토링 과정에서 자동차의 움직임에 대해 전략 패턴을 적용시켜 보았습니다.)

이번 미션에서 객체를 설계하는데 이 객체가 어떤 기능까지 모두 수행해야 하는지에 대해 정확하게 판단하는게 어려웠습니다

RacingCar 클래스와 RacingCar 객체를 여러개 만들어서 자동차 경주를 모두 수행하는 RacingCarGame 클래스를 설계하였습니다.이렇게 하면 RacingCarGame는 game play 역할도 하게 되고, 자동차 객체를 여러개만드는 역할도 하게 되었습니다. 아직 객체의 역할과 책임을 분리하라는 말을 완벽하게 이해하지 못한것같습니다

1. 이번 미션에서 객체의 역할, 책임, 협력에 따른 자동차 미션의 올바른 객체지향적 설계가 무엇인지 궁금합니다!
2. public 메소드에 대한 테스트코드가 하나밖에 나오지 않았습니다ㅠ. 테스트코드를 위한 public한 메소드를 다시 작성하는건 잘못된 방법같은데 private하거나 void 한 기능의 테스트코드는 구체적으로 어떻게 하면 좋을지 궁금합니다!

2021-05-25 12:55 UTC, kwj1270 requested changes
안녕하세요 혜원님,
전체적으로 코드를 고심해서 작성했다는 것이 많이 느껴졌습니다.
특히 `validation` 부분과 `전략패턴`을 사용하는 부분   
그리고 질문주신 것처럼 각 클래스의 역할과 책임을 최대한 알맞게 가져가시려는 
노력이 많이 보였습니다 👍 👍 👍 (테스트는 완벽하네요 ㅎㅎ)

다만 몇 가지 고려해볼 점이 있는 것 같습니다.  
아래 정리해보았으니 확인 부탁드릴게요 :)   

1. 람다 사용시 의미가 있는 이름 사용
2. 매직 넘버를 `private` 상수로    
3. 프리미티브 대신, 레퍼런스 타입 사용(값 검증)
4. 적절한 `Optional` 사용
5. 일급 컬렉션 사용(추천)  

그리고, 질문 주신 내용을 보고 정말 고민을 많이 하셨다는게 느껴졌습니다.   
사실, 객체가 어떤 기능까지 수행해야 하는지를 처음부터 알기는 매우 힘들어요  
이 부분에 대해서 `노하우`가 크게 좌우되는 부분이기에 
`이거는 이거다`라고 말씀을 드리기는 조금 힘들 것 같아요 😢
다만, 제가 추천드리는 방법은 `시나리오를 작성하기` 와 `처음부터 구현하기`에요  

[객체지향의 사실과 오해](https://github.com/SSAFY5thGwangJu4C/TDD-with-Java/blob/main/reference/objectOrientedProgramming.md)   

이러한 내용을 질문 주신 것을 보면 이미 읽어보신 것 같지만   
예시를 위해 한번 더 언급해볼게요 :)  
   
상황을 시나리오로 나타내면 아래와 같아요  
    
1. 손님은 커피를 주문한다.
2. 캐시어는 주문 받고 바리스타에게 주문서를 바리스타에게 전한다.
3. 바리스타는 커피를 제조하고 캐시어에게 전달한다.
4. 캐시어는 커피를 고객에게 전달한다.  
  
![image](https://user-images.githubusercontent.com/50267433/119497980-1b937e00-bda0-11eb-8b86-e284d365d475.png)

여기서 `객체간의 협력`이 나오는데   
바리스타를 기준으로만 이야기를 해볼게요   
바리스타는 `주문을 받는다` , `커피를 건네준다`와 같은 역할로 `캐시어와 소통`해요  
대신, `커피를 만든다`와 같은 역할은 본인만 알고 있으면 되는 것이죠  

이를 코드로 표현하면 `다른 객체와 소통하는 역할`은 `public 메서드`로     
`혼자만 알면 되는 역할`은 `private 메서드`와 같은 형태가 될 거에요   
여기서 힌트를 얻어서 `행동(메서드)`을 기준으로 클래스를 바라보면  
자연스레 객체간의 `책임`, `역할`, `협력`에 대해서 감을 잡으실거라 생각이듭니다. 😊

그 다음으로 `처음부터 구현해보기`라는 주제에 대해서 말씀드리자면  
이름 그대로, `3단계` -> `4단계` -> `5단계`를 진행할 때 처음부터 구현해보는거에요  
처음부터 구현을 하면서 무조건 `TDD의 원칙`에 맞게,  
즉 `테스트 케이스` -> `실제 구현` -> `리팩터링`을 지키면서 코딩을 작성하면   
이전에 자신이 구현했던 것과 달리 더 효율적인 코드를 작성할 수 있을거에요 
실제로 저도 이 방법을 통해서 가장 크게 성장했고, 
`NextStep`에서도 가장 추천하는 방법이에요  
간혹, 어떤 분들은 코드를 다시 짜는 것에 대해서 거부감을 느끼곤 하는데   
막상 처음부터 TDD로 다시 작성해보면     
작성할 때마다 크게 성장하고 있는 것을 느낄 수 있습니다.     

`테스트 메서드의 수`에 대해서 답변을 드리자면     
코드를 더 세분화 시키고(한 가지 기능만 하는 메서드로 분리, 클래스를 분리)   
프리미티브 타입들을 객체로 만드는 작업을 하면 더 많아질거에요 :)   
우선, 이번에 리뷰 드린 `일급 컬렉션`을 만들어보시면    
더 많은 테스트가 생길 것이기에 한번 경험해보셨으면 좋겠습니다 :)   
     
`private` 와 `void`에 대해서 테스트를 진행하는 것은 권장하지 않고 있어요 :)     
왜냐하면 `move()`와 같이 `trace`값을 1 증가 시키는 것은  
`getTrace() == 2`와 같은 방법으로도 테스트가 가능하기 때문이죠      

그래도, 이 부분에 대해서 혜원님처럼 테스트를 진행하는 방법도 있는데  
이 부분에 대해서는 링크를 남겨드릴게요 :)  
   
[참고 사이트-댓글을 보세요](https://www.slipp.net/questions/253)    
   
많이 바쁘신 와중에도 열심히 참여해주셔서 정말 감사합니다.  
혜원님 덕분에 저도 힘내서  리뷰를 할 수 있었고   
혜원님의 성장을 위해서 좀 더 성의를 다해서 리뷰를 진행했기에   
이 부분은 좋게 봐주시면 감사하겠습니다 😉 

앞으로도 열심히 해봅시다 아자아자 화이팅!!!! 🔥🔥🔥

2021-05-25 12:55 UTC, kwj1270 commented on src/main/java/step3/domain/RacingCarGame.java
> +    private List<RacingCar> racingCars;
`컬렉션 프레임워크`를 이용해서 구현을 해주셨군요 💯 💯 💯   
사실 이대로 진행을 해도 비즈니스 로직을 구현하는데 무리는 없지만  
더 좋은 방법이 있어서 코멘트를 남겼습니다 :) 

```suggestion
    private RacingCars racingCars;
```   
제가 `TDD`를 진행하면서 배운 것 중 가장 좋은 기법 중 하나라고 생각하는 `일급 컬렉션`이라는 기법이 있어요     
아래 참고 사이트와 제가 정리한 내용이 있으니 확인 부탁드릴게요 😉

[참고 사이트1](https://jojoldu.tistory.com/412)     
[참고 사이트2](https://github.com/my-next-step/lecture-and-retrospect/blob/main/%EC%9D%BC%EA%B8%89%20%EC%BB%AC%EB%A0%89%EC%85%98.md)

2021-06-07 15:38 UTC, hyewon1012 commented on src/main/java/step2/domain/StringOperation.java
> +        }
Optional은 반환할 값이 없을때 null 대신 래퍼로 감싸는 타입인데 완전히 잘못 사용하고있었군요..
Optional 의 탄생배경을 생각하며 적절하게 사용하겠습니다!!

2021-06-07 15:46 UTC, hyewon1012 commented on src/main/java/step2/domain/StringOperation.java
> +        int result = operand.get(FIRST_INDEX);
넵! 유의하겠습니다!!

2021-06-10 15:27 UTC, hyewon1012 commented
안녕하세요 우재님! 언급해주신 내용들 공부하여 적용시켜보려 노력했습니다!

1. InputView 에서 검증로직을 분리했습니다. 사용자의 입력값을 검증하는 역할을 가진 InputValidate  클래스를 생성하였습니다.만약 사용자의 입력이 늘어난다면 저의 InputValidate 클래스는 OCP원칙을 위반한것같다고 생각하는데, 사용자의 입력이 늘어난다면 유효성 검증은 어떤식으로 처리하는게 좋을까요? 이전에 학습한 전략패턴을 사용자 입력 검증에서도 동일하게 사용해야 하는걸까요?

2. 자동차 경주에 사용되는 여러 자동차를 생성하는것을 모두 관리하는 역할을 가진 CarGenerator  클래스를 생성하였습니다.  CarGenerator의 역할을 위와 같이 정의하였는데, CarGenerator는 단순하게 RacingCar 객체를 여러개 생성하는것이라고 생각하여 RacingCar가 가져야 하는 move 메소드, trace 멤버 변수들은 RacingCar 객체에서 따로 관리하도록 하였습니다. 이와 같이 설계하다보니 CarGenerator로 자동차 객체들을 만들때 RacingCar 객체가 각각 moveStrategy 구현체를 주입받게되는데... 더 나은 방법이 있을지 궁금합니다!

3. 불변객체에 대해 혹시 참고할만한 내용들이 있을까요?

2021-06-12 04:22 UTC, kwj1270 reviewed
혜원님 3단계 미션까지 수고하셨습니다 👍 

단, 몇 가지 고민해 볼 사항에 대해서 코멘트 남겼으니 확인 부탁드릴게요!
 
그리고 질문에 대해 답변드리자면 아래와 같아요 
1. 사용자에게서 값을 받으면 이를 처리하기 위해 `검증할 클래스`를 만드신 것 같네요 
그리고 여기서 `사용자 입력이 많아지면 클래스도 많아지고 변경사항도 생기지 않나? ` 
 라는 고민을 하신것 같아요  
 사실 이 부분에 대해서 코멘트를 많이 남겼는데  
`일급 컬렉션` `프리미티브 래퍼 클래스`는 **검증 로직을 분리한 클래스가 아니에요**    
`일급 컬렉션` `프리미티브 래퍼 클래스`는 **비즈니스 로직을 수행하는 `도메인 클래스`** 에요   
 `도메인 클래스` 이기에 `검증 + 비즈니스 로직`을 처리하는 작업을 한다고 보시면 됩니다.
 
 예를 들면)  
 `Round round = new Round(InputView.numberOfCar)`로 처리하고 
 `Round` 클래스는 생성자 안에서 validate 메서드를 만들어서 검증을하고 

```java
while(round.hasNext() {
   
    move로직();
    출력로직();

    round.next();
}
```
이런식으로 처리한다면 고민 하신 부분들을 해결될 것 같아요 
  
2. 2번의 답변도 1번과 비슷한 부분이 있다고 생각이 들고 
대신 `RacingCar 객체가 각각 moveStrategy 구현체를 주입받게되는데... 더 나은 방법이 있을지 궁금합니다!`에 대해서는 `move()`를 사용할 때 전략패턴을 사용하도록 해보는 방식이 좋을 것 같아요 :) 

3. 불변 객체에 대해서는 [제가 정리한 링크](https://github.com/springframework-sprout/JPA-Programming/blob/main/09%20%EA%B0%92%20%ED%83%80%EC%9E%85.md#%EB%B6%88%EB%B3%80-%EA%B0%9D%EC%B2%B4)를 남기고 필요하시다면 따로 제가 알려드릴게요 :)

2021-06-12 04:22 UTC, kwj1270 commented on src/main/java/step3/domain/RacingCarGame.java
> +    }
앞서 언급했듯이 Cars의 move() 메서드를 만들고 해당 코드를 넣어주면 좋을 것 같아요!

2021-06-12 04:22 UTC, kwj1270 commented on src/main/java/step3/ui/InputView.java
> +        round = new InputValidate(inputRound).getInput();
`View` 의 역할 중 하나는 `상태를 저장하지 않는다`에요 😢  
값을 입력받은 다음 단순히 반환하는게 좋을 것 같아요

2021-06-12 04:22 UTC, kwj1270 commented on src/main/java/step3/ui/ResultView.java
> +    }
출력 부분이 깔끔하고 완벽하네요 💯 💯 💯

2021-06-12 04:23 UTC, merged

2021-06-13 07:29 UTC, hyewon1012 commented on src/main/java/step3/domain/CarsGenerator.java
> +    }
넵!! 다시 학습하여 적용했습니다!
제가 작성한건 일급컬렉션이 아닌 단순 객체였군요..
우재님과 성규님 코드를 보고 잘못된점을 알게되었습니다!! 일급컬렉션은 상태와 핵심 로직을 각각 관리할수있다는점 확실히 이해했습니다!!

2021-06-13 07:31 UTC, hyewon1012 commented on src/main/java/step3/ui/InputView.java
> +        round = new InputValidate(inputRound).getInput();
넵!! 위의 코멘트를 통해 코드를 계속 수정하니 UI쪽에서 멤버변수를 가지고 있을 필요가 사라졌네요.. 코드에 반영하겠습니다!