[ssafy-java-racingcar] - step.3 자동차 미션(1단계) 코드리뷰 부탁드립니다.
SSAFY5thGwangJu4C/ssafy-java-racingcar pull request #16
Opened 2021-06-01 09:11 UTC by KimSeongKyu

안녕하세요 우재님. step.3 자동차 미션(1단계) 코드리뷰 부탁드립니다.

이번 미션을 진행하면서 singleton 패턴과 static 메소드를 어떻게 상황에 맞게
사용해야 할 지 많이 고민하게 되었고 아래와 같이 정리해 보았습니다.

[singleton 패턴 vs static 클래스]
- static 메소드는 전역 메소드이기 때문에 Integer.parseInt()와 같이 어플리케이션 내 모든 곳에서 동일한 논리로
기능을 수행해야 한다. 하지만 singleton 패턴은 결국 객체를 이용하는 것, 즉 논리적 사고가 가능한 대상으로,
어떠한 기능 및 동작을 함에 있어 객체의 논리적 판단에 따라 기능을 수행할 수 있다.

위의 정리에 기반하여 service 패키지 내의 MovementConditionProvider와 MovementDecisionMaker는 singleton 패턴을 이용하였고 domain 패키지 내의 CarFactory는 static 메소드를 이용하여 구현했습니다.

혹시 제가 정리한 내용이 잘못되었거나 부족한 부분이 있다면 같이 피드백 해주시면 감사하겠습니다 :)

2021-06-03 03:18 UTC, kwj1270 reviewed
안녕하세요 성규님 이번 미션 오로지 본인의 힘으로만 고민하고 코드를 작성한게 눈에 보이네요 :) 👍🏻👍🏻👍🏻 
사실, 넥텝 과정을 진행하시는 분들도 레퍼런스가 많기에 참고를 많이 하시지만  
성규님 같은 경우는 오롯이 자신의 실력을 증진하실 것 같아 기대가 됩니다. ☺️ 😉   

우선 저 같은 경우는 `싱글톤`과 `static` 에 대해서  메모리 관점으로 생각을 해요   
이전 미션에서 처럼 `utils`관련 클래스들은 단순히 `static 연산 메서드`만을 제공하고 이들은 프로그램 시작부터 끝까지 존재해도 괜찮죠  
다만, 싱글톤은 싱글톤 자체도 일종의 객체이기에 더 이상 사용되지 않으면 GC의 대상이 되어 메모리에서 삭제를 바랄 수 있고    
대부분의 싱글톤은 내부에 상태(`인스턴스 변수`)를 포함하고 있으니 상태가 필요한 경우에 주로 이용하죠     
물론, `인스턴스 변수가 없으면 무조건 static으로 해야해!` 라는건 아닙니다. :)      

그리고 최근에는 `객체지향`이라는 개념에 `static`이 맞지 않다고 보는 추세라    
최대한 클래스와 객체를 만들고 사용하고 있어요 이 점도 챙겨두시면 좋을 것 같아여 :) 
추가로, [참고 링크](https://m.blog.naver.com/ss1511/221586516299) 남길게요.

2021-06-03 03:18 UTC, kwj1270 commented on src/main/java/step3/service/RacingManager.java
> +    }
race 메서드는 public 임에도 테스트가 힘들어 질 것 같아요
랜덤값을 생성하고 움직이는 전략에 대해서는 더 높은 계층에서 넘겨주는 것은 어떨까요?

2021-06-03 03:18 UTC, kwj1270 commented on src/test/java/step3/service/RacingManagerTest.java
> +    private static MovementConditionProvider mockMovementConditionProvider;
위에서 언급했듯이 Mock 테스트는 지양하고 있어요 이러한 요쇼들은 제거해주세요 🙌🏻 

단위 테스트는 최대한 다른 객체에 종속적이지 않고 도메인 자체만을 테스트하는 것이 좋아요   
`MovementConditionProvider`가 단위 테스트에 들어옴으로써 해당 테스트는 
`MovementConditionProvider`가 있어야만 동작하는 테스트가 되버리죠   
이를 해결하기 위해서 메서드에 조건을 받을 수 있는 파라미터를 만들고 
`디자인 패턴`을 이용하고 `인터페이스`를 이용하고 `람다`를 이용합니다 :)   

이부분은 앞서 언급했던 `전략패턴`으로 변환하시면서 차차 느껴지실거에요

2021-06-03 15:08 UTC, kwj1270 requested changes
request changes

2021-06-06 07:40 UTC, KimSeongKyu commented on src/main/java/step2/operator/OperatorSelector.java
> +                .get();
이 부분에서 대해서 저는 해당 로직이 수행되기 이전에 ExpressionTokenizer 클래스에서 수식을 토큰화를 하는데,
이 때 연산자가 +,-,*,/가 아닐 경우 예외를 발생시킵니다.
그래서 해당 로직을 수행될 때는 이미 기호에 맞는 연산자만 넘어오기 때문에 orElseThrow 대신 get으로 처리했습니다.

2021-06-06 07:43 UTC, KimSeongKyu commented on src/main/java/step2/operator/DivideOperator.java
> +
Thread-Safe 하다는 것만 생각하여 Eagar Initialization으로 singleton 인스턴스를 생성하였는데
메모리 관련해서는 생각하지 못했네요!!
좋은 피드백 감사합니다!😄

2021-06-06 07:51 UTC, KimSeongKyu commented on src/main/java/step3/Application.java
> +        List<Car> cars = CarFactory.createCars(numberOfCars);
정말 좋은 글 감사합니다.
이전까지는 리스트를 단순히 배열과 다르게 요소의 개수가 가변적이라는 것이 장점 때문에
개발자 입장에서 메모리 관리가 편해서 사용한다고 생각했습니다.
그래서 Kotlin을 공부했을 때 왜 리스트의 기본 속성이 Immutable이고 MutableList라는 것을 따로 두어 사용하는지
의문이였는데 이것도 불변 객체 때문이라는 것을 이해하게 되었습니다.😀

2021-06-10 15:20 UTC, kwj1270 requested changes

2021-06-12 03:45 UTC, kwj1270 reviewed
성규님 이제는 거의 피드백을 드릴게 없을 정도로 거의 완벽하시네요.  👍 👍 👍
다만, 일급 컬렉션에 대해서 조금 생각해볼 점들이 있어서 이부분에 대해서 피드백 드렸습니다 :) 
이제 마지막 미션만 남았으니 조금만 더 힘내서 이번 과정 잘 수료하시기를 진심으로 바랍니다 :)   

그리고 질문 주신 내용에 대해서 매우 좋은 부분이기에 한번 고심해봐야할 것 같아요.
개인적인 생각으로는 일급 컬렉션에서 또한 새로운 일급 컬렉션을 만들어서 반환하는 것은 아닐까 생각이 드네요
현재 성규님 코드에는 Cars 가 move() 하는 메소드가 존재하지 않아요 
일급 컬렉션 또한 비즈니스 로직을 수행하는 코드이기에 
비즈니스 로직인` move()`를 정의하고 일급 컬렉션을 반환하도록 하는 방법이 좋을 것 같아요 :)

2021-06-12 03:45 UTC, kwj1270 commented on src/main/java/step3/domain/car/Cars.java
> +public final class Cars {
Cars 의 역할이 매우 빈약한 것 같아요
예를 들면 List<Car>를 반환한뒤에 `move()`를 동작시키는 것 보다 
Cars 내부에서 `move()` 동작시키는게 좋을 것 같네요

2021-06-12 03:45 UTC, kwj1270 commented on src/main/java/step3/Application.java
> +                    );
객체지향 생활체조 원칙에서 depth는 1단계만 허용해요 
그리고 이 같은 작업도 테스트를 해야하는데 진행하지 못하겠네요 😢 
Cars 클래스 안에서 동작시켜보면 어떨까요?

2021-06-12 03:45 UTC, merged