[ssafy-java-racingcar] - step.4 자동차 미션(2단계) 코드리뷰 부탁드립니다.
SSAFY5thGwangJu4C/ssafy-java-racingcar pull request #17
Opened 2021-06-16 12:43 UTC by KimSeongKyu

안녕하세요 우재님. step.4 자동차 미션(2단계) 코드리뷰 부탁드립니다.

이번 미션을 진행하면서 생성자 오버로딩에 대해 궁금한 점이 있습니다.
먼저, 제가 작성하고자 하는 코드는 다음과 같았습니다.
```java
public Cars(final Names names) {
    validateNamesAreNull(names);
    this(names.values());
}

public Cars(final List<Name> names) {
    this(createCars(names));
}

public Cars(final List<Car> cars) {
    this.cars = cars;
}
```
하지만 생성자 오버로딩을 하면 다음과 같은 문제점이 있습니다.
1. 오버로딩된 생성자를 호출하는 경우 파라미터 검증을 할 수 없습니다.
```java
public Cars(final Names names) {
    validateNamesAreNull(names);
    this(names.values());
}
```
2. List의 Generic 타입이 다르더라도 생성자 오버로딩이 불가능합니다.
```java
public Cars(final List<Name> names) {
    this(createCars(names));
}

public Cars(final List<Car> cars) {
    this.cars = cars;
}
```
이러한 경우, 다음과 같이 생성자의 다양성을 제한하더라도 검증을 우선시 하는 것이 더 나은 코드인지 궁금합니다.
```java
public Cars(final Names names) {
    validateNamesAreNull(names);
    this.cars = createCars(names.values()));
}
```

그리고 이전까지 진행했던 내용을 바탕으로 처음부터 코드를 작성해 보니
확실히 스터디를 진행하기 이전보다 성장했다는 느낌이 들어 뿌듯했습니다.
이렇게 성장할 수 있는 좋은 기회 주셔서 감사합니다 😄

2021-06-17 05:23 UTC, kwj1270 requested changes
안녕하세요 성규님 
저 또한 나날이 성장하시는 모습에 제가 다 뿌듯하고 매우 보람찬 경험이 되었습니다 ☺️  
긴 시간이었고 다소 지루할 수 있음에도 지치지 않고 열심히 참여해주셔서 진심으로 감사드리고 
이번 경험을 통해 앞으로도 더 좋은 개발자로 성장해서 좋은 곳에 취직하셨으면 좋겠습니다. 🙏
(나중에 사이드 프로젝트 같이해요 🙄 ㅎㅎㅎㅎㅎ) 

우선 질문 주신 내용에 답을 하자면 이 부분은 개인의 취향이 조금 있을 것 같아요
저 같은 경우도 아래와 같이 작성할 것 같지만, 저희가 생각 못하는 다른 방법이 있을 것 같기도 하네요 ㅎㅎ
코드에 정답이 없듯이 이런 부분에 대해서는 조금 유연하게 생각을 가지셔도 괜찮을 것 같아요 

```java
public Cars(final Names names) {
    validateNamesAreNull(names);
    this.cars = createCars(names.values());
}
```
또는, (검증을 한번만 하니 이쪽이 더 괜찮을 수도 있겠네요)
```java
public Cars(final Names names) {
    this(createCars(names.values()));
}
```
사실, 이정도로 작성을 해주셨다면 이전 step 같은 경우 바로 pass 하지만 
마지막 미션이기에 몇 가지 생각해볼점들을 남겨두었고 금방 수정하실수 있을 것 같아요 :)

2021-06-17 05:23 UTC, kwj1270 commented on src/main/java/step4/Application.java
> +public class Application {
[재귀를 이용한 무중단 프로그램 만들기](https://github.com/my-next-step/lotto-java/blob/kwj1270/src/main/java/step4/LottoGame.java)

해당 링크의 코드를 보고
에러가 발생해도 이를 재귀적으로 처리해서 무중단으로 돌 수 있는 프로그램을 만들어 주시면 좋을 것 같아요 :)

2021-06-18 08:03 UTC, KimSeongKyu commented on src/main/java/step4/Application.java
> +    }
Instream으로 리팩토링 하려고 하면서 
`람다를 사용하면 내부적으로 사용되는 변수는 final 속성을 만족해야 하기 때문에 cars = cars.move()와 같은 가변 코드를 사용할 수 없다.`는 새로운 것을 알게 되었네요!

그리고 TotalRound를 Round 클래스로 바꾸고, 라운드 진행 방식을 우재님이 추천해주신 방식처럼
`while(round.hasNext())`로 리팩토링을 했더니 코드가 훨씬 직관적으로 변한 것 같아서 기분이 좋네요 😀

2021-06-18 08:05 UTC, KimSeongKyu commented on src/main/java/step4/domain/winners/Winners.java
> +                .mapToInt(car -> car.position().value())
`디미터 법칙`이라는 새로운 것을 알게 되었네요!
피드백 감사합니다😀

2021-06-18 08:08 UTC, kwj1270 commented on src/main/java/step4/Application.java
> +    }
스트림의 기본 철칙이 `final`한 값만 사용할 수 있다는거에요(final 안붙여도 후에 값이 안바뀌면 유사 final 로 처리)  
저도 올해 초에 백기선님의 스터디 하면서 알았는데 처음에 이해 안가다가 스트림을 사용하면서 알게되었어요 :)  

역할과 책임을 지속적으로 생각하면 더 좋은 도메인을 작성하실 수 있고  
더 나아가 `도메인 주도 개발 DDD` 까지 이어질 수 있는 기반을 마련하시게 될거에요 :)

2021-06-18 08:30 UTC, KimSeongKyu commented on src/main/java/step4/domain/car/Cars.java
> +    private final List<Car> values;
처음에 값이 나타내는 이름을 변수명으로 사용했더니 names.name().name()과 같이
names 내에 name이 있는데 name이 또 있다는 것이 어색하다는 느낌을 받아 value로 값 자체를 나타냈었는데,
디미터 법칙을 적용하고 나니 그러한 문제가 자연스럽게 해결되었네요!👍

2021-06-18 09:35 UTC, kwj1270 reviewed
성규님 이제 더이상 피드백 드릴게 없네요 완벽히 구현해주셨습니다 :)   
5주간 긴 시간이었음에도 열심히 참여해주셔서 그리고 적극적인 자세로 임해주셔서 정말 감사합니다.
이번 TDD 미션은 여기서 종료하지만, 다음에도 기회가 된다면 같이 공부 할 수 있으면 좋겠습니다. 
수고 많으셨습니다.!!! 🥇  

**추가로**   
TDD에 대해서 더 깊이 공부하고 싶으시다면,
`테스트 주도 개발` 관련 책이나 `NextStep TDD 과정`을 진행하시면 도움이 되실거에요 :)

2021-06-18 09:35 UTC, merged