[4단계 자동차 미션] 코드 리뷰 부탁드립니다
SSAFY5thGwangJu4C/ssafy-java-racingcar pull request #18
Opened 2021-06-16 15:29 UTC by hyewon1012

안녕하세요 우재님!!

우선 저번에 일급컬렉션 다시 이해하는데 도움주셔서 정말 감사합니다!

이번 미션 진행하면서 구현해야할 시나리오를 작성하고 최대한 TDD 라이프사이클로 코드를 작성해보았는데, 구현 하면 할수록 시나리오에서 수정될부분이 많아지고, test 코드도 나중엔 다시 작성하게되는..? 그런 일들이 일어나서 이 방식이 TDD인지 헷갈리는것같습니다..ㅎㅎ

이번 미션 진행하면서 궁금한 사항은 아래와 같습니다!!

1. 우승자를 관리하고 우승자를 찾아내는 역할을 가진 Winner클래스를 만들었는데, 우승자가 여러명 있을 수 있기 때문에 먼저, 가장 큰 값을 찾기위해 반복문을 돌고, 그 다음으로 최대값과 같은 position을 가진 객체를 찾기위해 반복문을 한번 더 돌게됩니다. 혹시 stream 문법에서 object 안에 object가 있는 value의 최대값을 찾을수있는 문법이 있는지 궁금합니다.

2. 자동차 경주 게임을 실행하는 RacingCarGame의 클래스에는 void 메소드인 playGame()만 존재합니다. 이 playGame 메소드를 테스트 할 방법이 없어서 테스트 코드가 작성하지 않았는데, 이렇게 여러 트랜잭션을 실행하는 서비스 코드는 어떻게 테스트 코드를 작성해야 하는지 궁금합니다!

3. MoveStrategy를 Functional Interface로 작성하였고 추상메소드인 move에 대한 테스트를 진행하기위해 기존의 void였던 move를 boolean 타입으로 바꿔 test를 진행했습니다. 이를 람다식으로 잘 표현을 못한것같은데.. 람다표현식에 대한 참고할만한 사이트가 있을까요?

2021-06-17 07:48 UTC, kwj1270 requested changes
안녕하세요 회원님 :) 
ㅎㅎㅎ 원래 그런 느낌이 드는게 정상이라고 생각해요. 
`TDD` 라는건 **설계를 진행하고 코드를 작성**하는 것이기에    
이미 **도메인과 비즈니스 로직이 무엇인지 파악된 상태**에서 쉽게 구현할 수 있거든요 
실제로 제가 미션을 진행할 때도 `자바지기`님께서 이에 대한 내용을 말씀해주셨는데 
작성하다가 잘 안 되면 `일단 다 구현` ->`다 지우기` -> `TDD 스타일로 처음부터 구현` 이런식으로 연습을 하라고 말씀해주셨어요.  
엄밀히 말하면 지금 당장은  `TDD`를 적용하시지 못한건 사실이지만 **TDD 능력을 얻기 위해 거치는 과정 ⭐️**이라 생각이 들고,   
2학기 프로젝트를 할 때나 개인 공부할 때 의식적으로 적용하시면 점점 좋아지실 것 같아요 :)  

우선, 질문에 답변드리자면 
1. 같은 경우, 충분히 고민해볼만한 점이에요
저도 그 부분이 의심스러워서 `stream().reduce()`도 사용하고, `Comparable`인터페이스도 구현했지만,  
결과적으로 2번 찾는 방법이 가장 나은 방법이었고, 혜원님께서도 이 부분 잘 작성해주셨답니다 :)  

2. 굉장히 좋은 질문이네요     
MVC 패턴으로 비유하자면 `RacingCarGame`는 `컨트롤러` 또는 `서비스` 클래스라고 생각이 듭니다.  
사실, `컨트롤러/서비스` 클래스들은 `프레임워크`와 `DB`에 강하게 연결되어 있기에 테스트를 하기 힘들어요   
이를 해결하기 위해 `Mock 프레임워크`를 사용해서 `가짜 객체`와 `행동`을 넣어서 테스트를 할 수는 있지만
이번 `TDD 과정`은 최대한 `자바 코드 자체만으로 테스트`를 하는 것이 목적이기에 이 부분은 테스트를 권하지는 않아요
그러니 이 부분에 대해서 `Mock 프레임워크`를 사용해서 테스트를 할 수 있구나 정도만 알고 가셔도 될 것 같아요  
만약 `Mock 프레임워크`에 대해서 공부하시고자 한다면 [제가 정리한 내용](https://github.com/springframework-sprout/THE_JAVA_TEST/tree/main/Mockito)을 참고하셔도 됩니다 :) 
 
3. 우선, `move()`를 `boolean 타입`으로 바꾸신건 테스트를 위함도 있으시겠지만 비즈니스로직을 위해 적용하신걸로 보입니다. 
람다에 대해서는 크게 노하우가 있는게 아니기 때문에 우선 제가 코멘트 단 부분을 보시면 좋을 것 같고  
[람다 정리한 내용](https://github.com/kwj1270/TIL_JAVA/blob/master/15%20Lambda.md)에 대해서 올릴테니 한 번 보시면 좋을 것 같고 궁금한 점 있으시면 언제든지 연락주세요 :)   
 
로직도 잘 구현해주셨고, 마지막으로 인사이트 드리기 위해 `Request changes` 드렸으니 
피드백 내용 한 번 봐주시면 감사하겠습니다 ☺️   
앞으로 마지막 한 단계 남았습니다. 지금까지 달려와주셔서 정말 감사드리고 화이팅입니다!!

2021-06-17 07:48 UTC, kwj1270 commented on src/main/java/step3/strategy/RandomMove.java
>      }
코드를 보게 되면 `0`과 `1`만 반환 하는 걸로 보이는데  
해당 메서드를 호출한 곳에서는 아래와 같은 메서드를 호출하고 있더라고요 

```java
        if(moveStrategy.move()){            
            position.goForward();        
        }
```
0과 1대신에 boolean 타입으로만 적용하셔도 괜찮을 것 같아요 :)

2021-06-20 10:35 UTC, hyewon1012 commented on src/main/java/step3/domain/Cars.java
> +    }
아 그렇네요 generateCars 메소드의 역할은 경주에 참여할 자동차를 생성하는건데 이걸 파라미터로 받으면 이 함수의 의미가 없군요.. 수정했습니다!!

2021-06-20 10:37 UTC, hyewon1012 commented on src/main/java/step3/domain/Round.java
> +        }
알고리즘문제풀때도 이렇게 썼는데 동일하게 적용시켜야겠네요!! 날카로운 지적 감사합니다!!

2021-06-20 10:42 UTC, hyewon1012 commented on src/main/java/step4/domain/RacingCar.java
> +    private String name;
Position은 위치 상태와 로직을 저장하고있기때문에 Position이라는 클래스를 따로 생성해주었는데 마찬가지로 name도 상태와 로직이 필요하군요..!! name만을 생성하고, name을 검증하는 로직이 있는 Name 클래스를 만드니 확실히 클래스들의 역할이 명확하게 분리되는것을 리팩토링을 통해 느꼈습니다!!

2021-06-20 11:09 UTC, hyewon1012 commented on src/main/java/step4/domain/Winner.java
> +                .filter(car -> car.getPosition().getPosition() == max)
디미터의법칙 처음 알았네요 감사합니다!!

```java
List<RacingCar> winners = racingCars.stream()
        .filter(car -> {
            Position position = car.getPosition();
            return position.getPosition() == max;
        }).collect(Collectors.toList());
```

코멘트 참고하여 위와 같이 바꿨습니다! 
이 경우는 연속해서 객체를 반환하지 않는다고 생각하는데, 디미터의 법칙에 해당하지 않는걸까요?!

2021-06-20 11:36 UTC, hyewon1012 commented on src/test/java/step3/RacingCarTest.java
> +        car.move(new RandomMove());
람다를 넣어 true/false로 구분하니깐 더 명확해지고 test case도 더 보충되네요..!! 적용하겠습니다!!

2021-06-20 12:12 UTC, hyewon1012 commented on src/main/java/step4/ui/InputView.java
> +    }
이 부분때문에 생성자를 오버로딩하는 필요성을 완전히 체화했습니다!! 감사합니다ㅎㅎ

2021-06-20 12:18 UTC, hyewon1012 commented
안녕하세요 우재님!!
보내주신 코멘트 참고하여 피드백 적용하였습니다!!
이번 미션으로 객체 지향적 프로그래밍과 좀 더 가까워진것같습니다!! 무엇보다도 처음 작성한 코드를 보니깐 왜 이렇게 작성했지..? 라는 코드가 정말 많았었네요..ㅎㅎ
특히 우재님의 지식 공유가 큰 도움이되었습니다 정말 감사합니다!!

이번 미션에서 궁금했던 점은 두가지가 있습니다! 

1. Winner 클래스에서 디미터의 법칙에 관한것입니다
코멘트 참고하여 아래와 같이 코드를 수정하였는데, 연속해서 객체를 반환하지 않으므로 디미터의 법칙을 잘 지킨코드인가요?
```java
List<RacingCar> winners = racingCars.stream()
        .filter(car -> {
            Position position = car.getPosition();
            return position.getPosition() == max;
        }).collect(Collectors.toList());
```

2. RacingCar 클래스는 Name 참조 변수와, Position 참조 변수를 가지고 있습니다. 여기서 getter 를 사용하여 Name, Position의 인스턴스를 가져오게 했는데 위와 같이 Winner 클래스에서 연속해서 get()을 두번쓴 이유가 현재 위치를 int 값으로 반환하는 로직은 Position이 가진 역할이라고 생각했기 때문입니다. 이 경우 RacingCar 객체가 위치 상태를 가져오고자 할때 Position의 get메소드를 통해 반환해야하는것일까요?
```java
//기존코드
public Position getPosition(){
        return this.position;
    }
//이 방식으로 해야할까요? 이렇게 하면 Position의 getter 코드는 필요가없는걸까요..?
public Position getPosition(){
        return this.position.getPosition(); // Position의 getter 호출
    }
```

2021-06-20 14:27 UTC, kwj1270 reviewed
혜원님 `로직` + `피드백 받은 내용으로 개선` 까지 잘 작성해주셨네요. 💯 
혜원님처럼 피드백을 적극적으로 받아들이고 개선해나가면서 성장해나가시는 모습을 보니 
스터디 진행자로서 매우 큰 보람을 느끼고 힘 낼 수 있었어요 정말 감사드려요 :)   

___
# 질문 

우선, 질문 주신 부분에 대해서 답변 드리겠습니다. (`1`, `2`번 질문 한번에 할게요)    
   
디미터의 법칙은 해결했으나 반대로 **스트림의 역할**과 **가독성에 문제**가 있을 수 있어요  
스트림은 파이프 방식으로 점진적으로 기능을 수행하므로 **각 파이프마다 한 개의 기능만을 수행**하는 것이 좋은데  
기존 코드는 `position객체를 가져온다`, `position의 값이 == max 인지 확인하다`라는 2가지의 기능이 있는 것을 알 수 있죠 
그렇기에 이를 `.map()`으로 전처리를 하고나서 `filter(position.getPosition() == max)`을 처리해주는게 좋을 것 같아요 :)  

```java
List<RacingCar> winners = racingCars.stream()
        .map(car -> car.getPosition())
        .map(position -> position.getPosition())
        .filter(position -> position == max)
        .collect(Collectors.toList());
```
이렇게 처리함으로써 `stream()`의 각 파이프는 한 개의 기능만을 수행할 수 있게 되었고 가독성 또한 좋아진걸 알 수 있죠  
```java
List<RacingCar> winners = racingCars.stream()
        .map(car -> car.getPosition())
        .filter(position -> position == max)
        .collect(Collectors.toList());
```
하지만 `map()`이 2번 쓰인다는건 불필요한 로직 호출이 있다는 것을 의미하므로   
혜원님이 2번 질문으로 작성해주신 코드를 적용한다면 코드가 더 깔끔해질 수 있죠 :)   
또한 혜원님이 말씀해주신 것처럼 `getter`가 사라지는 코드가 되는거죠 ㅎㅎㅎ 
참고로 `Position`의 `getter`는 남아있지만 이는 필수적인 것이므로 이 부분에 대해서는 유연하게 생각하셔도 될 것 같아요 :)    

___  
# 수고하셨습니다. 👩‍🎓
      
**혜원님! 5주라는 시간 동안 정말 수고 많으셨습니다.**     
아마 혜원님이 `처음 작성했던 코드`와 `지금의 코드`를 보면 확연히 달라졌다는걸 느끼셨을거에요     
저는 이 모든게 **혜원님이 5주라는 시간 동안 미션에 적극적으로 임해주셨기에 이뤄낸거라 생각이 듭니다.**       
그러니 이 자세와 이 마음가짐을 잃지 않고 열심히 준비하셔서 꼭 원하시는 바를 이루기를 진심으로 응원하겠습니다
    
이번 TDD 미션은 여기까지 하겠습니다.  
앞으로도 `궁금한 사항`이나 `이야기`, `고민 거리`있으시면 편하게 연락주세요 :) 
수고하셨습니다 😊

2021-06-20 14:27 UTC, merged